uniqush:
  container_name: uniqush-server
  image: beevelop/uniqush
  links:
    - redis
  ports:
    - "9899:9898"
  restart: always
  environment:
    - REDIS_HOST=redis
  entrypoint: /usr/bin/envsubst < /opt/uniqush/uniqush-push-source.conf > /opt/uniqush/uniqush-push.conf


redis:
  container_name: uniqush-redis
  image: redis:alpine
  restart: always
