uniqush:
  container_name: uniqush-server
  image: beevelop/uniqush
  links:
    - redis
  ports:
    - "9899:9898"
  restart: always
  environment:
    - REDIS_HOST=redis
  entrypoint: /opt/uniqush/entrypoint.sh


redis:
  container_name: uniqush-redis
  image: redis:alpine
  restart: always
